apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001  # Choose a port in the range 30000-32767
  type: LoadBalancer